name: Building on latest windows

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    
      
    - name: Install dependencies
      run: make install_dependencies    
    - name: Compile
      run: make
