name: Building on latest ubuntu

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

      
    - name: Install dependencies
      run: make install_dependencies    
    - name: Compile
      run: make
