name: Building on latest macos
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: Install dependencies
      run: make install_dependencies    
    - name: Compile
      run: make
