name: Check if our unit tests are successful

on:
  push:
    branches: [ "main" , "nightly" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest
    
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19

    steps:      
    - name: Check our unit tests
      run: |
          cd utility/test && go test ./...
        